[package]
name = "fsrpad"
version = "0.1.0"
edition = "2018"
default-run = "fsrpad"

[[bin]]
name = "client"

[dependencies]
gnuplot = "0.0.34"
i2cdev = "0.4"

[dependencies.clap]
version = "3.0.0-beta.1"
default-features = false
features = ["std", "derive"]
